// Mocks generated by Mockito 5.0.10 from annotations
// in sample_app/test/login/login_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'login_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void login({String? email, String? pass}) => super.noSuchMethod(
      Invocation.method(#login, [], {#email: email, #pass: pass}),
      returnValueForMissingStub: null);
}
